project_id = "mhbmxvgcdzhqwpznmgei"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.whatsapp-subscription]
verify_jwt = false

[functions.store-webhook]
verify_jwt = false